services:
  mysql:
    container_name: mysql-bsn
    image: mysql:8
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: book_social_network
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql:
    driver: local

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/book_social_network
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 83ca27376e8c4d03b0b41ace8bce5c7d980b0b4d8ea4814b20bfd9559770cdf1
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8088